### ISSUE TITLE
How to run ?

### ISSUE THREAD

**Issue by DALDEI** [fungusakafungus/cloudformation-jsonschema#2]
I cant find a way to contact the author "fungusakafungus" so I created a Wiki page and entering an Issue.  Any suggestions on how to run ? I am new to python but guessed a few things and was able to run without error 
   python tools.py

This silently produced a 0 length resource.json file

Any clues how to debug this ? what the command line is ? Is this actually the command to run ?
anything at all ... just trying to see if this will save me a bit of time - but if I cant figure out how to run it let alone see any errors ... well ... it wont ... 
Not looking for perfection just a tiny bump up to avoid rewriting exactly the same thing from scratch

**Comment by fungusakafungus** [comment]
Oh. Sorry for not reacting on time! I wasn't watching the repo and thought no one it's interested in this! I'll update the status of the project and continue working on this. For now it is just a prototype, not really usable.

**Comment by fungusakafungus** [comment]
Resolved in 19b602857a449702f0fcb7e30039c8b8e1d857de :)
